# Token almaq üçün API məlumatları
token:
  url: "https://yoda.az/api/get_token"
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

# Kanal konfiqurasiyası
channels:
  - channelID: "aztv"
    channelName: "AZTV"
    channelSource: "https://str.yodacdn.net/aztv/video.m3u8"
    channelProgramme: "https://azepg.ddns.net/aztv/15_days_archive__aztv_desc.xml"
    channelIconC: "/logos/aztv.svg"
    channelIconM: "/logos/aztv.svg"
  - channelID: "ictimai"
    channelName: "İctimai"
    channelSource: "https://str.yodacdn.net/ictimaitv/video.m3u8"
    channelProgramme: "https://azepg.ddns.net/aztv/15_days_archive__itv_desc.xml"
    channelIconC: "/logos/itv.png"
    channelIconM: "/logos/itv.png"
  # Qalan kanallar burada...
  - channelID: "space"
    channelName: "Space"
    channelSource: "https://str.yodacdn.net/space/video.m3u8"
    channelProgramme: "https://azepg.ddns.net/aztv/15_days_archive__space_desc.xml"
    channelIconC: "/logos/space.png"
    channelIconM: "/logos/space.png"

# Çıxış faylının adı
output_file: "updated_channels.json"

# Zamanlama və manual yenilənmə parametrləri
schedule:
  auto_refresh: false  # Avtomatik yenilənməni deaktiv et
  interval_hours: 1    # Avtomatik yenilənmə intervalı (əgər aktivdirsə)
